import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { PROJECT_ROOT } from './paths';

const PREVIEW_EXTENSION_ROOT = join(
  PROJECT_ROOT,
  'temp',
  'vscode-theme-preview',
);
const PREVIEW_USER_DATA_ROOT = join(
  PROJECT_ROOT,
  'temp',
  'vscode-theme-preview-user-data',
);
const PREVIEW_DARK_LABEL = 'Vayeate Live Preview';
const PREVIEW_LIGHT_LABEL = 'Vayeate Live Preview Light';

/**
 * Runtime request from the renderer to build and open the preview extension.
 */
export interface ThemePreviewHostRequest {
  displayName: string;
}

function validateDisplayName(value: unknown): string {
  if (typeof value !== 'string') {
    throw new Error('Preview theme name must be a string');
  }

  const displayName = value.trim();
  if (displayName.length === 0 || displayName.length > 120) {
    throw new Error('Preview theme name must be between 1 and 120 characters');
  }

  return displayName;
}

/**
 * Builds the temporary VS Code color-theme extension manifest.
 *
 * @param displayName - Current selected theme name.
 */
export function buildThemePreviewExtensionManifest(displayName: string) {
  const validatedDisplayName = validateDisplayName(displayName);
  return {
    name: 'vayeate-live-theme-preview',
    displayName: `${validatedDisplayName} — Vayeate Live Preview`,
    description: `Live preview extension generated by Vayeate Theme Studio for ${validatedDisplayName}.`,
    publisher: 'vayeate-theme-studio',
    version: '0.0.0',
    engines: { vscode: '^1.76.0' },
    categories: ['Themes'],
    contributes: {
      themes: [
        {
          label: PREVIEW_DARK_LABEL,
          uiTheme: 'vs-dark',
          path: './themes/active-color-theme.json',
        },
        {
          label: PREVIEW_LIGHT_LABEL,
          uiTheme: 'vs',
          path: './themes/active-light-color-theme.json',
        },
      ],
    },
  };
}

/**
 * Builds isolated VS Code user settings that activate the generated dark preview theme.
 */
export function buildThemePreviewUserSettings() {
  return {
    'workbench.colorTheme': PREVIEW_DARK_LABEL,
    'window.autoDetectColorScheme': false,
  };
}

/**
 * Writes the temporary color-theme extension manifest and launches it in VS Code.
 *
 * @param request - Current theme metadata supplied by the renderer.
 */
export async function openThemePreviewHost(
  request: ThemePreviewHostRequest,
): Promise<void> {
  const displayName = validateDisplayName(request?.displayName);
  const userSettingsDir = join(PREVIEW_USER_DATA_ROOT, 'User');
  await Promise.all([
    mkdir(join(PREVIEW_EXTENSION_ROOT, 'themes'), { recursive: true }),
    mkdir(userSettingsDir, { recursive: true }),
  ]);

  const manifest = buildThemePreviewExtensionManifest(displayName);
  const settings = buildThemePreviewUserSettings();

  await Promise.all([
    writeFile(
      join(PREVIEW_EXTENSION_ROOT, 'package.json'),
      `${JSON.stringify(manifest, null, 2)}\n`,
      'utf-8',
    ),
    writeFile(
      join(userSettingsDir, 'settings.json'),
      `${JSON.stringify(settings, null, 2)}\n`,
      'utf-8',
    ),
  ]);

  const command = process.platform === 'win32' ? 'code.cmd' : 'code';
  const examplesRoot = join(PROJECT_ROOT, '..', 'examples');
  const child = spawn(
    command,
    [
      '--new-window',
      `--extensionDevelopmentPath=${PREVIEW_EXTENSION_ROOT}`,
      `--user-data-dir=${PREVIEW_USER_DATA_ROOT}`,
      examplesRoot,
    ],
    {
      cwd: PREVIEW_EXTENSION_ROOT,
      detached: true,
      shell: process.platform === 'win32',
      stdio: 'ignore',
      windowsHide: true,
    },
  );
  await new Promise<void>((resolve, reject) => {
    child.once('spawn', resolve);
    child.once('error', reject);
  });
  child.unref();
}
