export {
  templateSchema,
  catalogReferenceSchema,
  colorVariableSchema,
  contrastVariableSchema,
  mappingSchema,
  type Template,
  type CatalogReference,
  type ColorVariable,
  type ContrastVariable,
  type Mapping,
  type TemplateName,
  type ColorVariableKey,
  type ContrastVariableKey,
} from './schemas.js';
