/** Catalog undo diff action types — registered on the universal undo processor. */
export const CATALOG_TOKEN_KEY_UPDATED = 'CATALOG_TOKEN_KEY_UPDATED' as const;
export const CATALOG_TOKENS_BULK_ADDED = 'CATALOG_TOKENS_BULK_ADDED' as const;
export const CATALOG_SOURCE_ADDED = 'CATALOG_SOURCE_ADDED' as const;
export const CATALOG_SOURCE_REMOVED = 'CATALOG_SOURCE_REMOVED' as const;
export const CATALOG_SOURCE_URL_UPDATED = 'CATALOG_SOURCE_URL_UPDATED' as const;
export const CATALOG_SOURCE_TYPE_UPDATED = 'CATALOG_SOURCE_TYPE_UPDATED' as const;
export const CATALOG_SOURCE_TOKEN_TYPE_UPDATED = 'CATALOG_SOURCE_TOKEN_TYPE_UPDATED' as const;
export const CATALOG_LOCKED = 'CATALOG_LOCKED' as const;
export const CATALOG_SYNCED = 'CATALOG_SYNCED' as const;
export const CATALOG_TOKEN_ADDED = 'CATALOG_TOKEN_ADDED' as const;
export const CATALOG_TOKEN_REMOVED = 'CATALOG_TOKEN_REMOVED' as const;
export const CATALOG_SEMANTIC_SELECTOR_ADDED = 'CATALOG_SEMANTIC_SELECTOR_ADDED' as const;
export const CATALOG_SEMANTIC_REGISTRY_ITEM_REMOVED = 'CATALOG_SEMANTIC_REGISTRY_ITEM_REMOVED' as const;
export const CATALOG_SEMANTIC_REGISTRY_TEXT_UPDATED = 'CATALOG_SEMANTIC_REGISTRY_TEXT_UPDATED' as const;
export const CATALOG_REVERTED_TO_VERSION = 'CATALOG_REVERTED_TO_VERSION' as const;
export const CATALOG_VERSION_DELETED = 'CATALOG_VERSION_DELETED' as const;
export const CATALOG_CREATED = 'CATALOG_CREATED' as const;

export const CATALOG_UNDO_ACTION_TYPES = [
  CATALOG_TOKEN_KEY_UPDATED,
  CATALOG_TOKENS_BULK_ADDED,
  CATALOG_SOURCE_ADDED,
  CATALOG_SOURCE_REMOVED,
  CATALOG_SOURCE_URL_UPDATED,
  CATALOG_SOURCE_TYPE_UPDATED,
  CATALOG_SOURCE_TOKEN_TYPE_UPDATED,
  CATALOG_LOCKED,
  CATALOG_SYNCED,
  CATALOG_TOKEN_ADDED,
  CATALOG_TOKEN_REMOVED,
  CATALOG_SEMANTIC_SELECTOR_ADDED,
  CATALOG_SEMANTIC_REGISTRY_ITEM_REMOVED,
  CATALOG_SEMANTIC_REGISTRY_TEXT_UPDATED,
  CATALOG_REVERTED_TO_VERSION,
  CATALOG_VERSION_DELETED,
  CATALOG_CREATED,
] as const;

export type CatalogUndoActionType = (typeof CATALOG_UNDO_ACTION_TYPES)[number];

/** Template undo diff action types — registered on the universal undo processor. */
export const TEMPLATE_COLOR_VARIABLE_ADDED = 'TEMPLATE_COLOR_VARIABLE_ADDED' as const;
export const TEMPLATE_CONTRAST_VARIABLE_ADDED = 'TEMPLATE_CONTRAST_VARIABLE_ADDED' as const;
export const TEMPLATE_GROUP_ADDED = 'TEMPLATE_GROUP_ADDED' as const;
export const TEMPLATE_COLOR_VARIABLE_REMOVED = 'TEMPLATE_COLOR_VARIABLE_REMOVED' as const;
export const TEMPLATE_CONTRAST_VARIABLE_REMOVED = 'TEMPLATE_CONTRAST_VARIABLE_REMOVED' as const;
export const TEMPLATE_VARIABLE_GROUP_REF_UPDATED = 'TEMPLATE_VARIABLE_GROUP_REF_UPDATED' as const;
export const TEMPLATE_CONTRAST_COMPARISON_SOURCE_UPDATED = 'TEMPLATE_CONTRAST_COMPARISON_SOURCE_UPDATED' as const;
export const TEMPLATE_GROUP_REMOVED = 'TEMPLATE_GROUP_REMOVED' as const;
export const TEMPLATE_SEMANTIC_VARIANT_ADDED = 'TEMPLATE_SEMANTIC_VARIANT_ADDED' as const;
export const TEMPLATE_MAPPING_REMOVED = 'TEMPLATE_MAPPING_REMOVED' as const;
export const TEMPLATE_SEMANTIC_VARIANT_KEY_UPDATED = 'TEMPLATE_SEMANTIC_VARIANT_KEY_UPDATED' as const;
export const TEMPLATE_MAPPING_COLOR_REF_SET = 'TEMPLATE_MAPPING_COLOR_REF_SET' as const;
export const TEMPLATE_MAPPING_CONTRAST_REF_SET = 'TEMPLATE_MAPPING_CONTRAST_REF_SET' as const;
export const TEMPLATE_MAPPING_GROUP_REF_SET = 'TEMPLATE_MAPPING_GROUP_REF_SET' as const;
export const TEMPLATE_CATALOG_TOGGLED = 'TEMPLATE_CATALOG_TOGGLED' as const;
export const TEMPLATE_CATALOG_VERSION_CHANGED = 'TEMPLATE_CATALOG_VERSION_CHANGED' as const;
export const TEMPLATE_LOCKED = 'TEMPLATE_LOCKED' as const;
export const TEMPLATE_CATALOGS_ALL_UPDATED = 'TEMPLATE_CATALOGS_ALL_UPDATED' as const;
export const TEMPLATE_CREATED = 'TEMPLATE_CREATED' as const;
export const TEMPLATE_VERSION_DELETED = 'TEMPLATE_VERSION_DELETED' as const;

export const TEMPLATE_UNDO_ACTION_TYPES = [
  TEMPLATE_COLOR_VARIABLE_ADDED,
  TEMPLATE_CONTRAST_VARIABLE_ADDED,
  TEMPLATE_GROUP_ADDED,
  TEMPLATE_COLOR_VARIABLE_REMOVED,
  TEMPLATE_CONTRAST_VARIABLE_REMOVED,
  TEMPLATE_VARIABLE_GROUP_REF_UPDATED,
  TEMPLATE_CONTRAST_COMPARISON_SOURCE_UPDATED,
  TEMPLATE_GROUP_REMOVED,
  TEMPLATE_SEMANTIC_VARIANT_ADDED,
  TEMPLATE_MAPPING_REMOVED,
  TEMPLATE_SEMANTIC_VARIANT_KEY_UPDATED,
  TEMPLATE_MAPPING_COLOR_REF_SET,
  TEMPLATE_MAPPING_CONTRAST_REF_SET,
  TEMPLATE_MAPPING_GROUP_REF_SET,
  TEMPLATE_CATALOG_TOGGLED,
  TEMPLATE_CATALOG_VERSION_CHANGED,
  TEMPLATE_LOCKED,
  TEMPLATE_CATALOGS_ALL_UPDATED,
  TEMPLATE_CREATED,
  TEMPLATE_VERSION_DELETED,
] as const;

export type TemplateUndoActionType = (typeof TEMPLATE_UNDO_ACTION_TYPES)[number];

/** Theme undo diff action types — registered on the universal undo processor. */
export const THEME_PALETTE_COLOR_ASSIGNED = 'THEME_PALETTE_COLOR_ASSIGNED' as const;
export const THEME_COLOR_VARIABLE_LIGHT_SET = 'THEME_COLOR_VARIABLE_LIGHT_SET' as const;
export const THEME_COLOR_VARIABLE_DARK_SET = 'THEME_COLOR_VARIABLE_DARK_SET' as const;
export const THEME_CONTRAST_VARIABLE_LIGHT_VALUE_SET = 'THEME_CONTRAST_VARIABLE_LIGHT_VALUE_SET' as const;
export const THEME_CONTRAST_VARIABLE_LIGHT_MIN_SET = 'THEME_CONTRAST_VARIABLE_LIGHT_MIN_SET' as const;
export const THEME_CONTRAST_VARIABLE_LIGHT_MAX_SET = 'THEME_CONTRAST_VARIABLE_LIGHT_MAX_SET' as const;
export const THEME_CONTRAST_VARIABLE_LIGHT_METHOD_SET = 'THEME_CONTRAST_VARIABLE_LIGHT_METHOD_SET' as const;
export const THEME_CONTRAST_VARIABLE_DARK_VALUE_SET = 'THEME_CONTRAST_VARIABLE_DARK_VALUE_SET' as const;
export const THEME_CONTRAST_VARIABLE_DARK_MIN_SET = 'THEME_CONTRAST_VARIABLE_DARK_MIN_SET' as const;
export const THEME_CONTRAST_VARIABLE_DARK_MAX_SET = 'THEME_CONTRAST_VARIABLE_DARK_MAX_SET' as const;
export const THEME_CONTRAST_VARIABLE_DARK_METHOD_SET = 'THEME_CONTRAST_VARIABLE_DARK_METHOD_SET' as const;
export const THEME_CONTRAST_USE_DARK_FOR_LIGHT_SET = 'THEME_CONTRAST_USE_DARK_FOR_LIGHT_SET' as const;
export const THEME_COLOR_USE_DARK_FOR_LIGHT_SET = 'THEME_COLOR_USE_DARK_FOR_LIGHT_SET' as const;
export const THEME_PALETTE_APPLY_TO_LIGHT_SET = 'THEME_PALETTE_APPLY_TO_LIGHT_SET' as const;
export const THEME_PALETTE_APPLY_TO_DARK_SET = 'THEME_PALETTE_APPLY_TO_DARK_SET' as const;
export const THEME_PALETTE_CLUSTER_COUNT_SET = 'THEME_PALETTE_CLUSTER_COUNT_SET' as const;
export const THEME_PALETTE_HUE_RECENTERED = 'THEME_PALETTE_HUE_RECENTERED' as const;
export const THEME_PALETTE_HUE_ADJUSTMENT_SET = 'THEME_PALETTE_HUE_ADJUSTMENT_SET' as const;
export const THEME_PALETTE_HUE_REFERENCE_SET = 'THEME_PALETTE_HUE_REFERENCE_SET' as const;
export const THEME_PANE_SELECTIONS_SET = 'THEME_PANE_SELECTIONS_SET' as const;
export const THEME_TEMPLATE_SET = 'THEME_TEMPLATE_SET' as const;
export const THEME_LOADED_TEMPLATE_SET = 'THEME_LOADED_TEMPLATE_SET' as const;
export const THEME_PREVIEW_TOKEN_REF_SET = 'THEME_PREVIEW_TOKEN_REF_SET' as const;
export const THEME_VERSION_INCREMENTED = 'THEME_VERSION_INCREMENTED' as const;
export const THEME_VERSION_DELETED = 'THEME_VERSION_DELETED' as const;
export const THEME_CREATED = 'THEME_CREATED' as const;

export const THEME_UNDO_ACTION_TYPES = [
  THEME_PALETTE_COLOR_ASSIGNED,
  THEME_COLOR_VARIABLE_LIGHT_SET,
  THEME_COLOR_VARIABLE_DARK_SET,
  THEME_CONTRAST_VARIABLE_LIGHT_VALUE_SET,
  THEME_CONTRAST_VARIABLE_LIGHT_MIN_SET,
  THEME_CONTRAST_VARIABLE_LIGHT_MAX_SET,
  THEME_CONTRAST_VARIABLE_LIGHT_METHOD_SET,
  THEME_CONTRAST_VARIABLE_DARK_VALUE_SET,
  THEME_CONTRAST_VARIABLE_DARK_MIN_SET,
  THEME_CONTRAST_VARIABLE_DARK_MAX_SET,
  THEME_CONTRAST_VARIABLE_DARK_METHOD_SET,
  THEME_CONTRAST_USE_DARK_FOR_LIGHT_SET,
  THEME_COLOR_USE_DARK_FOR_LIGHT_SET,
  THEME_PALETTE_APPLY_TO_LIGHT_SET,
  THEME_PALETTE_APPLY_TO_DARK_SET,
  THEME_PALETTE_CLUSTER_COUNT_SET,
  THEME_PALETTE_HUE_RECENTERED,
  THEME_PALETTE_HUE_ADJUSTMENT_SET,
  THEME_PALETTE_HUE_REFERENCE_SET,
  THEME_PANE_SELECTIONS_SET,
  THEME_TEMPLATE_SET,
  THEME_LOADED_TEMPLATE_SET,
  THEME_PREVIEW_TOKEN_REF_SET,
  THEME_VERSION_INCREMENTED,
  THEME_VERSION_DELETED,
  THEME_CREATED,
] as const;

export type ThemeUndoActionType = (typeof THEME_UNDO_ACTION_TYPES)[number];
